#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lojaonline.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Loja")]
	public partial class LojaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable(Table instance);
    partial void UpdateTable(Table instance);
    partial void DeleteTable(Table instance);
    partial void InsertClick(Click instance);
    partial void UpdateClick(Click instance);
    partial void DeleteClick(Click instance);
    partial void InsertQuest(Quest instance);
    partial void UpdateQuest(Quest instance);
    partial void DeleteQuest(Quest instance);
    #endregion
		
		public LojaDataContext() : 
				base(global::Lojaonline.DATA.Properties.Settings.Default.LojaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LojaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LojaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LojaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LojaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table> Tables
		{
			get
			{
				return this.GetTable<Table>();
			}
		}
		
		public System.Data.Linq.Table<Click> Clicks
		{
			get
			{
				return this.GetTable<Click>();
			}
		}
		
		public System.Data.Linq.Table<Quest> Quests
		{
			get
			{
				return this.GetTable<Quest>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
	public partial class Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ID_FOTO;
		
		private string _APARECE;
		
		private string _NAME;
		
		private string _FOTO_URL;
		
		private string _ID_LOJA;
		
		private string _NOME_LOJA;
		
		private string _NOME_PESSOA;
		
		private string _FOTO_PERFIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_FOTOChanging(string value);
    partial void OnID_FOTOChanged();
    partial void OnAPARECEChanging(string value);
    partial void OnAPARECEChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnFOTO_URLChanging(string value);
    partial void OnFOTO_URLChanged();
    partial void OnID_LOJAChanging(string value);
    partial void OnID_LOJAChanged();
    partial void OnNOME_LOJAChanging(string value);
    partial void OnNOME_LOJAChanged();
    partial void OnNOME_PESSOAChanging(string value);
    partial void OnNOME_PESSOAChanged();
    partial void OnFOTO_PERFILChanging(string value);
    partial void OnFOTO_PERFILChanged();
    #endregion
		
		public Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FOTO", DbType="VarChar(MAX)")]
		public string ID_FOTO
		{
			get
			{
				return this._ID_FOTO;
			}
			set
			{
				if ((this._ID_FOTO != value))
				{
					this.OnID_FOTOChanging(value);
					this.SendPropertyChanging();
					this._ID_FOTO = value;
					this.SendPropertyChanged("ID_FOTO");
					this.OnID_FOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APARECE", DbType="VarChar(50)")]
		public string APARECE
		{
			get
			{
				return this._APARECE;
			}
			set
			{
				if ((this._APARECE != value))
				{
					this.OnAPARECEChanging(value);
					this.SendPropertyChanging();
					this._APARECE = value;
					this.SendPropertyChanged("APARECE");
					this.OnAPARECEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(MAX)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTO_URL", DbType="VarChar(MAX)")]
		public string FOTO_URL
		{
			get
			{
				return this._FOTO_URL;
			}
			set
			{
				if ((this._FOTO_URL != value))
				{
					this.OnFOTO_URLChanging(value);
					this.SendPropertyChanging();
					this._FOTO_URL = value;
					this.SendPropertyChanged("FOTO_URL");
					this.OnFOTO_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOJA", DbType="VarChar(MAX)")]
		public string ID_LOJA
		{
			get
			{
				return this._ID_LOJA;
			}
			set
			{
				if ((this._ID_LOJA != value))
				{
					this.OnID_LOJAChanging(value);
					this.SendPropertyChanging();
					this._ID_LOJA = value;
					this.SendPropertyChanged("ID_LOJA");
					this.OnID_LOJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME_LOJA", DbType="VarChar(MAX)")]
		public string NOME_LOJA
		{
			get
			{
				return this._NOME_LOJA;
			}
			set
			{
				if ((this._NOME_LOJA != value))
				{
					this.OnNOME_LOJAChanging(value);
					this.SendPropertyChanging();
					this._NOME_LOJA = value;
					this.SendPropertyChanged("NOME_LOJA");
					this.OnNOME_LOJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME_PESSOA", DbType="VarChar(MAX)")]
		public string NOME_PESSOA
		{
			get
			{
				return this._NOME_PESSOA;
			}
			set
			{
				if ((this._NOME_PESSOA != value))
				{
					this.OnNOME_PESSOAChanging(value);
					this.SendPropertyChanging();
					this._NOME_PESSOA = value;
					this.SendPropertyChanged("NOME_PESSOA");
					this.OnNOME_PESSOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTO_PERFIL", DbType="VarChar(MAX)")]
		public string FOTO_PERFIL
		{
			get
			{
				return this._FOTO_PERFIL;
			}
			set
			{
				if ((this._FOTO_PERFIL != value))
				{
					this.OnFOTO_PERFILChanging(value);
					this.SendPropertyChanging();
					this._FOTO_PERFIL = value;
					this.SendPropertyChanged("FOTO_PERFIL");
					this.OnFOTO_PERFILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Click")]
	public partial class Click : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CLICK;
		
		private string _ID_FOTO;
		
		private string _ID_LOJA;
		
		private System.Nullable<System.DateTime> _DATA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CLICKChanging(int value);
    partial void OnID_CLICKChanged();
    partial void OnID_FOTOChanging(string value);
    partial void OnID_FOTOChanged();
    partial void OnID_LOJAChanging(string value);
    partial void OnID_LOJAChanged();
    partial void OnDATAChanging(System.Nullable<System.DateTime> value);
    partial void OnDATAChanged();
    #endregion
		
		public Click()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLICK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CLICK
		{
			get
			{
				return this._ID_CLICK;
			}
			set
			{
				if ((this._ID_CLICK != value))
				{
					this.OnID_CLICKChanging(value);
					this.SendPropertyChanging();
					this._ID_CLICK = value;
					this.SendPropertyChanged("ID_CLICK");
					this.OnID_CLICKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FOTO", DbType="NVarChar(250)")]
		public string ID_FOTO
		{
			get
			{
				return this._ID_FOTO;
			}
			set
			{
				if ((this._ID_FOTO != value))
				{
					this.OnID_FOTOChanging(value);
					this.SendPropertyChanging();
					this._ID_FOTO = value;
					this.SendPropertyChanged("ID_FOTO");
					this.OnID_FOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOJA", DbType="NVarChar(250)")]
		public string ID_LOJA
		{
			get
			{
				return this._ID_LOJA;
			}
			set
			{
				if ((this._ID_LOJA != value))
				{
					this.OnID_LOJAChanging(value);
					this.SendPropertyChanging();
					this._ID_LOJA = value;
					this.SendPropertyChanged("ID_LOJA");
					this.OnID_LOJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA
		{
			get
			{
				return this._DATA;
			}
			set
			{
				if ((this._DATA != value))
				{
					this.OnDATAChanging(value);
					this.SendPropertyChanging();
					this._DATA = value;
					this.SendPropertyChanged("DATA");
					this.OnDATAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Quest")]
	public partial class Quest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_QUEST;
		
		private string _ID_LOJA;
		
		private string _ID_FOTO;
		
		private System.Nullable<System.DateTime> _DATA;
		
		private string _OPTION;
		
		private string _LIKE;
		
		private string _REACT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_QUESTChanging(int value);
    partial void OnID_QUESTChanged();
    partial void OnID_LOJAChanging(string value);
    partial void OnID_LOJAChanged();
    partial void OnID_FOTOChanging(string value);
    partial void OnID_FOTOChanged();
    partial void OnDATAChanging(System.Nullable<System.DateTime> value);
    partial void OnDATAChanged();
    partial void OnOPTIONChanging(string value);
    partial void OnOPTIONChanged();
    partial void OnLIKEChanging(string value);
    partial void OnLIKEChanged();
    partial void OnREACTChanging(string value);
    partial void OnREACTChanged();
    #endregion
		
		public Quest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_QUEST", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_QUEST
		{
			get
			{
				return this._ID_QUEST;
			}
			set
			{
				if ((this._ID_QUEST != value))
				{
					this.OnID_QUESTChanging(value);
					this.SendPropertyChanging();
					this._ID_QUEST = value;
					this.SendPropertyChanged("ID_QUEST");
					this.OnID_QUESTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOJA", DbType="NVarChar(MAX)")]
		public string ID_LOJA
		{
			get
			{
				return this._ID_LOJA;
			}
			set
			{
				if ((this._ID_LOJA != value))
				{
					this.OnID_LOJAChanging(value);
					this.SendPropertyChanging();
					this._ID_LOJA = value;
					this.SendPropertyChanged("ID_LOJA");
					this.OnID_LOJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FOTO", DbType="NVarChar(MAX)")]
		public string ID_FOTO
		{
			get
			{
				return this._ID_FOTO;
			}
			set
			{
				if ((this._ID_FOTO != value))
				{
					this.OnID_FOTOChanging(value);
					this.SendPropertyChanging();
					this._ID_FOTO = value;
					this.SendPropertyChanged("ID_FOTO");
					this.OnID_FOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA
		{
			get
			{
				return this._DATA;
			}
			set
			{
				if ((this._DATA != value))
				{
					this.OnDATAChanging(value);
					this.SendPropertyChanging();
					this._DATA = value;
					this.SendPropertyChanged("DATA");
					this.OnDATAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[OPTION]", Storage="_OPTION", DbType="NVarChar(50)")]
		public string OPTION
		{
			get
			{
				return this._OPTION;
			}
			set
			{
				if ((this._OPTION != value))
				{
					this.OnOPTIONChanging(value);
					this.SendPropertyChanging();
					this._OPTION = value;
					this.SendPropertyChanged("OPTION");
					this.OnOPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[LIKE]", Storage="_LIKE", DbType="NVarChar(50)")]
		public string LIKE
		{
			get
			{
				return this._LIKE;
			}
			set
			{
				if ((this._LIKE != value))
				{
					this.OnLIKEChanging(value);
					this.SendPropertyChanging();
					this._LIKE = value;
					this.SendPropertyChanged("LIKE");
					this.OnLIKEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REACT", DbType="NVarChar(50)")]
		public string REACT
		{
			get
			{
				return this._REACT;
			}
			set
			{
				if ((this._REACT != value))
				{
					this.OnREACTChanging(value);
					this.SendPropertyChanging();
					this._REACT = value;
					this.SendPropertyChanged("REACT");
					this.OnREACTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
